<?php View::partial('bootstrap/modal') ?>
<div id="update_info" class="span11">
	<?php view::content() ?>

	<div class="well">
		<div>
			<?php Print html::link("configuraciones/otras", "<i class=' icon-arrow-left'></i> Regresar a Configuraciones", "class='btn btn-warning'") ?>
			<?php Print html::link("tagresor/add", "<i class='icon-plus'></i> Nuevo Tipo de Agresor", "id='add' class='btn btn-primary' data-toggle='modal' data-target='#myModal'") ?>
		</div>
	</div>
	<table class="table table-bordered table-hover">
		<thead>
			<tr>
				<th>id</th>
				<th>Tipo de Agresor</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($tagresor as $tagresor): ?>
			<tr>
				<td><?php Print $tagresor->id ?></td>
				<td><?php Print html::link("tagresor/edit/".$tagresor->id, $tagresor->tagresor, " class='edit' data-toggle='modal' data-target='#myModal'") ?></td>
				<td><?php Print Js::linkAction("del/".$tagresor->id, '<i class="icon-remove"></i> Eliminar') ?></td>
			</tr>
			<?php endforeach ?>
		</tbody>
	</table>
</div>
