<?php Print Form::open() ?>
	<div class="modal-header">
		<a class="close" data-dismiss="modal">&times;</a>
		<h3>Edición de Usuario</h3>
	</div>

  	<div class="modal-body">
		<div class="controls">
			<?php Print Form::hidden('usuarios.id') ?>
			<label>Usuario</label>
			<?php Print Form::text('usuarios.usuario', "Placeholder='Usuario' class='span3'") ?>
			<?php Print Form::hidden('usuarios.pass') ?>

			<label>Nombre</label>
			<?php Print Form::text('usuarios.nombre', "Placeholder='Nombre' class='span3'") ?>

			<label>Apellido</label>
			<?php Print Form::text('usuarios.apellido', "class='span3'") ?>

			<label>E-mail</label>
			<?php Print Form::text('usuarios.email',  "class='span5'") ?>

			<label>Rol de Usuario</label>
			<?php Print Form::dbSelect('usuarios.rol_id') ?>
		</div>
  	</div>

	<div class="modal-footer">
		<?php Print Form::submit('Salvar Cambios', "class='btn btn-primary'") ?>
		<!--<a class="btn btn-primary" onclick="$('.modal-body > form').submit();">Guardar Cambios</a>-->
		<a class="btn" data-dismiss="modal">Close</a>
	</div>
<?php Print Form::close() ?>


