
<style type="text/css">
	<!--
	.h-images li{
		float: left;
		list-style: none;
	}
	-->
</style>
<div class="span3">
	<h2 style="text-align: center">Sistema de Alertas</h2>
	<h6 style="text-align: center">de Violación a la libertad de expresión en Honduras</h6>
</div>


<div class="span8">
	<ul class="h-images">
		<li><?php Print HTML::link("http://clibrehonduras.com", Html::img('clibre3.jpg', 'logos', "class='logos'")) ?></li>
		<li><?php Print HTML::link("http://conexihon.info", Html::img('conexihon3.jpg', 'logos', "class='logos'"))?></li>
		<li><?php Print HTML::link("http://www.opensocietyfoundations.org", Html::img('open3.jpg', 'logos', "class='logos'")) ?></li>
	</ul>
</div>



