<style type="text/css">
	<!--
		.footer{font-size: 10px; color:gray;}
	-->
</style>
<hr />
<div class="footer">
	<p>
		C-Libre es una coalición de periodistas y miembros de la sociedad civil constituida para promover y defender la libertad de expresión y el derecho a la información en Honduras. Quienes integramos C-Libre, estamos convencidos que en la construcción de un Estado de Derecho es imprescindible la existencia de un periodismo ético, de investigación, fiscalizador de la gestión pública, que se desempeñe en un ambiente de seguridad y acceso libre a la información y que promueva un régimen de opinión pública que haga valer su Derecho a la Información.Esta alerta es distribuida a través de diversas redes nacionales, regionales e internacionales. Para mayor información comunicarse al Comité por la Libre Expresión (C-Libre), al correo electrónico alertas@clibrehonduras.com, para sus comentarios acerca de esta y otras alertas, visite
		<?php print html::link('www.clibrehonduras.com', 'www.clibrehonduras.com'); ?>
		,
		<?php print html::link('www.conexihon.info', 'www.conexihon.info'); ?></p>
</div>