<?php View::partial('bootstrap/modal') ?>
<div id="update_info" class="span11">
<?php view::content() ?>
</div>

<div class="well">
	<div>
		<?php Print html::link("configuraciones/otras", "<i class=' icon-arrow-left'></i> Regresar a Configuraciones", "class='btn btn-warning'") ?>
		<?php Print html::link("agresion/add", "<i class='icon-plus'></i> Nuevo Tipo de Sujeto Agredido", "id='add' class='btn btn-primary' data-toggle='modal' data-target='#myModal'") ?>
	</div>
</div>

<table class="table table-bordered">
	<thead>
		<tr>
			<th>id</th>
			<th>Tipo de Agresor</th>
			<th>Categoria</th>
			<th>Eliminar</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($agresion as $agresion): ?>
		<tr>
			<td><?php Print $agresion->id ?></td>
			<td><?php Print html::link("agresion/edit/".$agresion->id, $agresion->agresion, "class='edit' data-toggle='modal' data-target='#myModal'") ?></td>
			<td><?php Print $agresion->acategoria->acategoria ?></td>
			<td><?php Print Js::linkAction("del/".$agresion->id, '<i class="icon-remove"></i> Eliminar') ?></td>
		</tr>
		<?php endforeach ?>
	</tbody>
</table>
</div>

