<?php Print Form::open() ?>

  <div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>
      <h3>Edición de Estado Judicial</h3>
  </div>

  <div class="modal-body">
    <div class="span4">
      <label>Estado Judicial</label>
      <?php Print Form::text("estadojudicial.estadojudicial", "class='span4'") ?>
    </div>
    <div class="span4">
      <label>Tipo</label>
      <?php Print Form::select("estadojudicial.tipo", $tipo) ?>
    </div>
  </div>

  <div class="modal-footer">
    <?php Print Form::submit('Salvar Cambios', "class='btn btn-primary'") ?>
    <!--<a class="btn btn-primary" onclick="$('.modal-body > form').submit();">Guardar Cambios</a>-->
    <a class="btn" data-dismiss="modal">Close</a>
  </div>

<?php Print Form::close() ?>