<?php Print Form::open() ?>

  <div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>
      <h3>Edicion de Tipo de Medio</h3>
  </div>

  <div class="modal-body">
    <div class="span4">
      <label>Nombre de Tipo de Medio</label>
      <?php Print Form::hidden("tipomediosistema.id") ?>
      <?php Print Form::text("tipomediosistema.tipomediosistema", "class='span4'") ?>
    </div>
  </div>

  <div class="modal-footer">
    <?php Print Form::submit('Salvar Cambios', "class='btn btn-primary'") ?>
    <!--<a class="btn btn-primary" onclick="$('.modal-body > form').submit();">Guardar Cambios</a>-->
    <a class="btn" data-dismiss="modal">Close</a>
  </div>

<?php Print Form::close() ?>
