
<div class="span11">

	<div class="well">
		<h3>Configuración de Listados</h3>
		<h5 class="text-info"><p>Por Favor, seleccione la el tipo o la categoria que desea editar</p></h5>
	</div>

	<?php print html::link('tagresor/', "Tipo de Agresor", "class='btn btn-large btn-block btn-inverse'") ?>
	<?php print html::link('tsagredido', "Tipo de Sujeto Agredido", "class='btn btn-large btn-block btn-inverse'") ?>
	<?php print html::link('agresion/', "Agresiones", "class='btn btn-large btn-block btn-inverse'") ?>
	<?php print html::link('categoria/', "Categoria de Agresiones", "class='btn btn-large btn-block btn-inverse'") ?>
	<?php print html::link('tipomediosistema/', "Tipo de Medio o Sistema", "class='btn btn-large btn-block btn-inverse'") ?>
	<?php print html::link('estadojudicial/', "Estado Judicial", "class='btn btn-large btn-block btn-inverse'") ?>

	<hr />
</div>

