<?php View::partial('bootstrap/modal') ?>

<div id="update_info" class="span11">
<?php view::content() ?>
</div>

<div class="well">
	<div>
		<?php Print html::link("configuraciones/otras", "<i class=' icon-arrow-left'></i> Regresar a Configuraciones", "class='btn btn-warning'") ?>
		<?php Print html::link("tagresor/add", "<i class='icon-plus'></i> Nuevo Tipo de Sujeto Agredido", "id='add' class='btn btn-primary' data-toggle='modal' data-target='#myModal'") ?>
	</div>	
	
</div>

<table class="table table-bordered">
	<thead>
		<tr>
			<th>id</th>
			<th>Tipo de Agresor</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($tsagredido as $tsagredido): ?>
		<tr>
			<td><?php Print $tsagredido->id ?></td>
			<td><?php Print html::link("tsagredido/edit/".$tsagredido->id, $tsagredido->tsagredido, "class='btn' data-toggle='modal' data-target='#myModal'") ?></td>
			<td><?php Print Js::linkAction("del/".$tsagredido->id, '<i class="icon-remove"></i> Eliminar') ?></td>
		</tr>
		<?php endforeach ?>
	</tbody>
</table>
</div>

